add HW4 file
eugene-okulik/Lolik pull request #3
Opened 2024-08-25 12:52 UTC by lolik7447

Ура, наконец-то пул реквесты без проблем.

2024-08-26 09:59 UTC, eugene-okulik requested changes

2024-08-26 09:59 UTC, eugene-okulik commented on homework/olga_maksimova/HW4/HW4.py
> +my_dict["dict"] = {'i am a tuple': 'good morning'}
Этой строкой ты не добавила в то, что находится под ключом dict новый элемент, а полностью заменила то, что хранится под ключом dict

2024-08-26 09:59 UTC, eugene-okulik commented on homework/olga_maksimova/HW4/HW4.py
> +my_dict["dict"] = {'i am a tuple': 'good morning'}
Ну и в задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-08-26 18:52 UTC, eugene-okulik requested changes

2024-08-26 18:52 UTC, eugene-okulik commented on homework/olga_maksimova/HW4/HW4.py
> +my_dict["dict"]['i am a tuple'] = 'good morning'
И всё еще:  
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-08-28 15:49 UTC, lolik7447 commented on homework/olga_maksimova/HW4/HW4.py
> +my_dict["dict"] = {'i am a tuple': 'good morning'}
Обновила, можно проверять

2024-08-29 10:00 UTC, eugene-okulik commented on homework/olga_maksimova/HW4/HW4.py
> +my_dict["dict"] = {'i am a tuple': 'good morning'}
А что изменилось? В ключе всё еще строка, а не кортеж с одним элементом.

2024-08-30 07:57 UTC, eugene-okulik approved these changes
:+1:

2024-08-30 07:58 UTC, merged