add hometasks files
eugene-okulik/Lolik pull request #7
Opened 2024-09-19 18:47 UTC by lolichka7447

не получилось сделать задачу №2

2024-09-20 08:03 UTC, eugene-okulik requested changes

2024-09-20 08:03 UTC, eugene-okulik commented on homework/olga_maksimova/HW8/Task2.py
> +# не получается
Ты просто что-то лишнее замутила с `count`: местами сбрасываешь его в 1, а там где нужно его наращивать, не наращиваешь, а делаешь `count += 0`  
Вот так всё ок:
```python
count = 1
for number in gen_fib():
    if count == 5:
        print(number)
    elif count == 200:
        print(number)
    elif count == 1000:
        print(number)
    elif count == 100000:
        print(number)
        break
    count += 1
```
Или что тебя смущает?

2024-09-20 16:42 UTC, lolichka7447 commented
Я сначала так сделала, но потом переделала :)

2024-09-21 07:36 UTC, eugene-okulik approved these changes

2024-09-21 07:36 UTC, merged